### PR TITLE
Remove android-specific codepath for getifaddrs

### PR DESCRIPTION
**Pull request by jamilbk**
Remove android-specific codepath for getifaddrs

This is not supported in Android 11+. Instead, use libc getifaddr which *allegedly* works with Android 7+.

See https://github.com/messense/if-addrs/issues/14

### CODE REVIEW

**Comment by jamilbk** [comment]
However, this issue on that same repo isn't very promising:

https://github.com/messense/if-addrs/issues/21

**Comment by thomaseizinger** [comment]
This is only deleting code. Is there a libc fallback that gets applied automatically?

**Comment by jamilbk** [comment]
@thomaseizinger That's a good question. This ffi is only for android, but the `ifaces` feature's unix codepath presumably calls `getifaddr` as well, so it's not clear to me. I do know it compiles and seems to run fine on Android.

`getifaddr` is [defined](https://github.com/firezone/webrtc/blob/fix-android/favor-getifaddrs-vs-ifaddrs-for-android-11/util/src/ifaces/ffi/unix/mod.rs#L87) like this:

```
extern "C" {
    pub fn getifaddrs(ifap: *mut *mut ifaddrs) -> ::std::os::raw::c_int;
}
```

I tried using `libc::getifaddrs` but that triggered a massive slew of refactoring that I attempted but ultimately gave up on.

This simple crate seems to do away with the need for this `ifaces` feature altogether: https://github.com/messense/if-addrs but it was taking me too long to refactor to that.

So I ended up with this PR.

**Comment by jamilbk** [comment]
One more good reason to roll our own minimal STUN/TURN client and do away with webrtc entirely.

**Comment by jamilbk** [comment]
@thomaseizinger This commit is successfully passing CI here: https://github.com/firezone/firezone/pull/1930

So I assume that `getifaddrs` in libc is found because of the `extern "C"` block? 🙃

**Comment by conectado** [comment]
> @thomaseizinger This commit is successfully passing CI here: [firezone/firezone#1930](https://github.com/firezone/firezone/pull/1930)
> 
> So I assume that `getifaddrs` in libc is found because of the `extern "C"` block? 🙃

This is similar to how C/C++ does it, `extern` blocks are just function declarations, then as part of the compilation the linker links to the declared functions if the library is included(which is in the case of glibc)

Here I [wrote an example with the write function](https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=ca1a30d8e6c8dc6e161bd9f22a17856f)

**Review by conectado — APPROVED** [review]
I think this looks good, we are sacrificing Android's <7 support which released 6 years ago, I think this is acceptable.

**Pull request merged**
